version: "3.5"

services:

  api:
    build: 
      context: ./backend
      dockerfile: ./compose/Dockerfile
    command: /start_api
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - 8010:8000
    volumes:
      - ./backend:/app

  db:
    image: postgres:14.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app

  redis:
    image: redis:6.2-alpine

  worker:
    build: 
      context: ./backend
      dockerfile: ./compose/Dockerfile
    command: /start_worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
      
  beat:
    build:
      context: ./backend
      dockerfile: ./compose/Dockerfile
    command: /start_beat
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app

  flower:
    build:
      context: ./backend
      dockerfile: ./compose/Dockerfile
    command: /start_flower
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - 5557:5555

volumes:
  postgres-data: {}
  
