version: "3.3"

services:

  postgres:
    image: postgres:14.5
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  backend:
    depends_on:
      - postgres
    env_file:
      - .env
    build: 
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  redis:
    image: redis:6.2-alpine

  celeryworker:
    build: 
      context: ./backend
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - backend
      - redis
  
  # flower:
  #   build: 
  #     context: ./backend
  #   command: celery -A celery_worker.celery flower --port=5555
  #   ports:
  #     - 5556:5555
  #   depends_on:
  #     - backend
  #     - redis
  #     - celeryworker

volumes:
  postgres-data: {}
  
